/**
 * TEST FIXTURES: hand-made, NOT real Chess.com games and NOT Lichess data.
 * They exist so the app and the tests can be exercised without a network.
 * The UI always labels them "TEST FIXTURE".
 */
import type { GameInfo, Puzzle } from './types';

const hdr = (white: string, black: string, result: string) =>
  `[Event "TEST FIXTURE (hand-made, not a real game)"]\n[Site "fixture"]\n[Date "2000.01.01"]\n[White "${white}"]\n[Black "${black}"]\n[Result "${result}"]\n\n`;

/** FIXTURE: I play Black and allow Scholar's mate with 3...Nf6?? (ply index 5). */
export const FIXTURE_GAME_BLACK: GameInfo = {
  id: 'fixture-black',
  url: 'https://example.invalid/fixture-black',
  pgn: hdr('FixtureOpponent', 'FixtureMe', '1-0') + '1. e4 e5 2. Bc4 Nc6 3. Qh5 Nf6 4. Qxf7# 1-0',
  white: 'FixtureOpponent',
  black: 'FixtureMe',
  myColor: 'b',
  opponent: 'FixtureOpponent',
  endTime: 946684800,
  timeClass: 'rapid',
  result: 'checkmated',
  isFixture: true,
};

/** FIXTURE: I play White and give a knight away with 9.Nxg5?. */
export const FIXTURE_GAME_WHITE: GameInfo = {
  id: 'fixture-white',
  url: 'https://example.invalid/fixture-white',
  pgn:
    hdr('FixtureMe', 'FixtureOpponent', '*') +
    '1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 4. d3 Bc5 5. Nc3 d6 6. Bg5 h6 7. Bh4 g5 8. Bg3 Nh5 9. Nxg5 hxg5 *',
  white: 'FixtureMe',
  black: 'FixtureOpponent',
  myColor: 'w',
  opponent: 'FixtureOpponent',
  endTime: 946684800,
  timeClass: 'rapid',
  result: 'unfinished',
  isFixture: true,
};

const selfPlayHdr = (white: string, black: string) =>
  `[Event "TEST FIXTURE (engine self-play, one inserted blunder; not a real game)"]\n[Site "fixture"]\n[Date "2000.01.01"]\n[White "${white}"]\n[Black "${black}"]\n[Result "*"]\n\n`;

/** FIXTURE: I play White. Generated by engine self-play; 13.Na2 is an inserted blunder in a middle-game position. */
export const FIXTURE_GAME_MIDDLE: GameInfo = {
  id: 'fixture-middle',
  url: 'https://example.invalid/fixture-middle',
  pgn: selfPlayHdr('FixtureMe', 'FixtureOpponent') + '1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Nf6 5. Nc3 Bb4 6. Nxc6 dxc6 7. Qxd8+ Kxd8 8. Bd2 a6 9. Bxa6 Rxa6 10. h3 Bxh3 11. Rxh3 Kc8 12. a3 Re8 13. Na2 Bxd2+ 14. Kxd2 Nxe4+ 15. Ke2 c5 16. Re3 *',
  white: 'FixtureMe',
  black: 'FixtureOpponent',
  myColor: 'w',
  opponent: 'FixtureOpponent',
  endTime: 946684800,
  timeClass: 'rapid',
  result: 'unfinished',
  isFixture: true,
};

/** FIXTURE: I play White. Same self-play game, cut later: 23.Ne3 is an inserted blunder in an end-game position. */
export const FIXTURE_GAME_END: GameInfo = {
  id: 'fixture-end',
  url: 'https://example.invalid/fixture-end',
  pgn: selfPlayHdr('FixtureMe', 'FixtureOpponent2') + '1. e4 e5 2. Nf3 Nc6 3. d4 exd4 4. Nxd4 Nf6 5. Nc3 Bb4 6. Nxc6 dxc6 7. Qxd8+ Kxd8 8. Bd2 a6 9. Bxa6 Rxa6 10. h3 Bxh3 11. Rxh3 Kc8 12. a3 Re8 13. f3 h6 14. O-O-O Bd6 15. Ne2 Nd7 16. Nd4 Be5 17. Bxh6 gxh6 18. Nf5 Bf4+ 19. Kb1 c5 20. g3 Bd6 21. Rxh6 Rxa3 22. bxa3 Ne5 23. Ne3 Nxf3 24. Nf5 Be5 25. Rh5 b6 26. Rd3 *',
  white: 'FixtureMe',
  black: 'FixtureOpponent2',
  myColor: 'w',
  opponent: 'FixtureOpponent2',
  endTime: 946684800,
  timeClass: 'rapid',
  result: 'unfinished',
  isFixture: true,
};

export const FIXTURE_GAMES: GameInfo[] = [FIXTURE_GAME_BLACK, FIXTURE_GAME_WHITE, FIXTURE_GAME_MIDDLE, FIXTURE_GAME_END];

/**
 * FIXTURE puzzle in the Lichess database format (FEN is BEFORE the opponent's
 * setup move). Hand-made knight fork, NOT from the Lichess puzzle database.
 * Moves[0] = black's setup move h7h6; the learner then plays Moves[1] = Nc7+.
 */
export const FIXTURE_PUZZLE: Puzzle = {
  id: 'FIXTURE-0001',
  fen: 'r3k3/7p/8/3N4/8/8/5PPP/6K1 b - - 0 1',
  moves: ['h7h6', 'd5c7', 'e8d7', 'c7a8'],
  rating: 800,
  themes: ['fork', 'short'],
  isFixture: true,
};
